version: "3.9"

services:
  mongodb:
    image: mongo:4.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app_network

  restapi:
    build: .
    container_name: restapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - app_network
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/mydatabase  # Environment variable for MongoDB URI

networks:
  app_network:
    driver: bridge
